install:
  - ps: choco install ant
build_script:
  - ant -version
  - ant prepare
  - ps: ./release.ps1
environment:
  CHOCO_APIKEY:
    secure: jRQ9WmVCdly4Z2gKEEq6ZIv+16er3lOM/JHejw+N4qzKkLZodGIXjchDfYLVQ1MK
